
import React, { ReactNode } from 'react';
import { Metadata } from 'next';
import Footer from '../Footer';
import Navbar from '../Navbar';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };


interface LayoutProps {
  children: ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <>
    <Navbar/>
      <main>{children}</main>
    <Footer/>
    </>
  );
};

export default Layout;
