// components/Layout.tsx
import React, { ReactNode } from 'react';
import { Metadata } from 'next';
import Navbar from '../Navbar';
import { useRouter } from 'next/router';
import { Analytics } from "@vercel/analytics/react"
import GoogleAnalytics from '../GoogleAnalytics';
import Footer from '../Footer';
import Sidebar from '../UserProfile/Sidebar';
import UserNav from '../UserProfile/UserNav';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
  const { pathname } = useRouter();


  // No Layout
  const noLayoutPaths = ['/session','/404'];

  if (noLayoutPaths.some((path) => pathname.startsWith(path))) {
    return (
      <>
        <GoogleAnalytics />
        {children}
        <Analytics />
      </>
    );
  }
  // Profile Layout
  const isProfileRoute = pathname.startsWith("/profile");

  if (isProfileRoute) {
    const pageTitle = pathname?.split("/")[2] || "Dashboard";

    return (
      <>
        <GoogleAnalytics />
        <main className="flex">
          <Sidebar />
          <div className="flex-1 ">
            <UserNav pageTitle={pageTitle} />
            <div className=' overflow-y-auto'>{children}</div>
          </div>
        </main>
        <Analytics />
      </>
    );
  }


  return (
    <main className='bg-white dark:bg-[#0f1116] text-gray-900 dark:text-white transition-colors duration-300 relative '>

       <Navbar />
      <GoogleAnalytics />


      {children}
      <Analytics />

      <Footer />

    </main>
  );
};

export default Layout;
